<?xml version="1.0" encoding="UTF-8"?>
<!--
  feed.xsl — RSS feed browser stylesheet for AI Press Review
  Deployment:
    1. Copy this file to docs/feed.xsl (GitHub Pages root)
    2. In docs/podcast-feed.xml (or generated by feed.py), add as SECOND LINE
       (after <?xml version="1.0"?> and BEFORE <rss ...>):
       <?xml-stylesheet type="text/xsl" href="/feed.xsl"?>
    3. Commit and push. The feed URL is then human-readable in any browser.

  Note: Firefox renders XSLT natively. Chrome/Edge do too for same-origin files.
  Safari also supports it. No JavaScript required for the base rendering.
  The copy-to-clipboard button uses a small inline JS snippet.
-->
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
  xmlns:atom="http://www.w3.org/2005/Atom"
  exclude-result-prefixes="itunes atom">

  <xsl:output method="html" version="5.0" encoding="UTF-8" indent="yes" />

  <!-- ROOT -->
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>RSS Feed — <xsl:value-of select="/rss/channel/title" /></title>
        <meta name="robots" content="noindex" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&amp;family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300&amp;display=swap" rel="stylesheet" />
        <style>
          :root {
            --bg: #09090b; --surface: #111113; --border: #1f1f23;
            --border-light: #2a2a30; --text: #e8e8ed; --text-secondary: #8a8a9a;
            --text-muted: #55555f; --accent: #c8a96e; --accent-dim: #8a6f3f;
            --accent-glow: rgba(200,169,110,0.08);
            --font-display: 'DM Serif Display', Georgia, serif;
            --font-body: 'DM Sans', system-ui, sans-serif;
          }
          *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            background: var(--bg); color: var(--text);
            font-family: var(--font-body); font-size: 15px; line-height: 1.7;
            -webkit-font-smoothing: antialiased;
          }

          /* HEADER */
          header { border-bottom: 1px solid var(--border); padding: 0 2rem; }
          .header-inner {
            max-width: 800px; margin: 0 auto;
            display: flex; align-items: center; justify-content: space-between; height: 56px;
          }
          .logo-link { text-decoration: none; display: flex; align-items: center; gap: 10px; }
          .logo-dot {
            width: 8px; height: 8px; border-radius: 50%; background: var(--accent);
            animation: pulse 3s ease-in-out infinite;
          }
          @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }
          .logo-text { font-family: var(--font-display); font-size: 1rem; color: var(--text); }
          .back-link {
            font-size: 0.78rem; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase;
            color: var(--text-secondary); text-decoration: none; transition: color 0.2s;
          }
          .back-link:hover { color: var(--accent); }

          /* RSS HERO */
          .rss-hero { padding: 3rem 2rem 2.5rem; border-bottom: 1px solid var(--border); }
          .rss-hero-inner { max-width: 800px; margin: 0 auto; }
          .rss-kicker {
            font-size: 0.68rem; font-weight: 500; letter-spacing: 0.14em; text-transform: uppercase;
            color: var(--accent); margin-bottom: 1rem; display: flex; align-items: center; gap: 0.5rem;
          }
          .rss-kicker::before {
            content: '';
            display: inline-block; width: 18px; height: 2px; background: var(--accent);
          }
          .rss-hero h1 {
            font-family: var(--font-display); font-size: clamp(1.6rem, 4vw, 2.2rem);
            color: var(--text); margin-bottom: 0.75rem; line-height: 1.2;
          }
          .rss-description { font-size: 0.9rem; color: var(--text-secondary); max-width: 560px; margin-bottom: 2rem; }

          /* COPY BOX */
          .copy-box {
            display: flex; align-items: center; gap: 0;
            background: var(--surface); border: 1px solid var(--border-light);
            border-radius: 6px; overflow: hidden; max-width: 580px;
          }
          .copy-label {
            font-size: 0.68rem; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase;
            color: var(--text-muted); padding: 0 1rem; white-space: nowrap; border-right: 1px solid var(--border);
          }
          .copy-url {
            flex: 1; font-size: 0.82rem; color: var(--accent);
            padding: 0.75rem 1rem; font-family: monospace; overflow: hidden;
            text-overflow: ellipsis; white-space: nowrap; user-select: all;
          }
          .copy-btn {
            background: none; border: none; border-left: 1px solid var(--border);
            cursor: pointer; padding: 0 1.1rem; height: 100%;
            font-size: 0.72rem; font-weight: 600; letter-spacing: 0.06em; text-transform: uppercase;
            color: var(--text-secondary); transition: color 0.2s, background 0.2s;
            white-space: nowrap;
          }
          .copy-btn:hover { color: var(--accent); background: var(--accent-glow); }
          .copy-btn.copied { color: #5cb85c; }

          /* STATS ROW */
          .stats-row {
            display: flex; gap: 2rem; margin-top: 2rem; flex-wrap: wrap;
          }
          .stat { font-size: 0.78rem; color: var(--text-muted); }
          .stat strong { color: var(--text-secondary); display: block; font-size: 1.1rem; font-weight: 500; }

          /* HOW TO SUBSCRIBE */
          .subscribe-row { display: flex; gap: 0.75rem; margin-top: 2rem; flex-wrap: wrap; }
          .sub-btn {
            display: inline-flex; align-items: center; gap: 0.45rem;
            font-size: 0.78rem; font-weight: 500; text-decoration: none;
            border: 1px solid var(--border-light); color: var(--text-secondary);
            padding: 0.5em 1em; border-radius: 4px; transition: color 0.2s, border-color 0.2s;
          }
          .sub-btn:hover { color: var(--accent); border-color: var(--accent-dim); }
          .sub-btn.primary {
            background: var(--accent); color: #09090b; border-color: transparent; font-weight: 600;
          }
          .sub-btn.primary:hover { opacity: 0.85; color: #09090b; }

          /* EPISODES */
          main { max-width: 800px; margin: 0 auto; padding: 0 2rem 5rem; }
          .episodes-header {
            padding: 2.5rem 0 1.25rem;
            font-size: 0.68rem; font-weight: 500; letter-spacing: 0.12em; text-transform: uppercase;
            color: var(--text-muted); border-bottom: 1px solid var(--border);
          }
          .episode-item {
            padding: 1.5rem 0;
            border-bottom: 1px solid var(--border);
            display: grid; grid-template-columns: 1fr auto; gap: 0.5rem 1.5rem; align-items: start;
          }
          .episode-title {
            font-family: var(--font-display); font-size: 1.05rem; color: var(--text);
            line-height: 1.3; text-decoration: none; transition: color 0.2s;
          }
          .episode-title:hover { color: var(--accent); }
          .episode-meta { font-size: 0.75rem; color: var(--text-muted); margin-top: 0.3rem; display: flex; gap: 1rem; }
          .episode-summary {
            font-size: 0.85rem; color: var(--text-secondary); margin-top: 0.6rem;
            line-height: 1.6; max-width: 560px; grid-column: 1;
          }
          .episode-duration {
            font-size: 0.72rem; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase;
            color: var(--text-muted); text-align: right; white-space: nowrap; padding-top: 0.2rem;
          }
          .episode-listen {
            display: inline-block; font-size: 0.72rem; font-weight: 600;
            letter-spacing: 0.06em; text-transform: uppercase;
            color: var(--accent); text-decoration: none; margin-top: 0.75rem;
            border-bottom: 1px solid var(--accent-dim); transition: border-color 0.2s;
          }
          .episode-listen:hover { border-color: var(--accent); }

          /* FOOTER */
          footer { border-top: 1px solid var(--border); padding: 1.5rem 2rem; text-align: center; }
          footer p { font-size: 0.75rem; color: var(--text-muted); }
          footer a { color: var(--text-muted); text-decoration: none; }
          footer a:hover { color: var(--accent); }

          @media (max-width: 600px) {
            .rss-hero, main, header { padding-left: 1.25rem; padding-right: 1.25rem; }
            .copy-label { display: none; }
            .episode-item { grid-template-columns: 1fr; }
            .episode-duration { text-align: left; }
            footer { padding: 1.25rem; }
          }
        </style>
      </head>
      <body>

        <header>
          <div class="header-inner">
            <a href="/" class="logo-link">
              <span class="logo-dot"></span>
              <span class="logo-text">AI Press Review</span>
            </a>
            <a href="/" class="back-link">← Back to site</a>
          </div>
        </header>

        <!-- HERO -->
        <div class="rss-hero">
          <div class="rss-hero-inner">
            <p class="rss-kicker">RSS Feed</p>
            <h1><xsl:value-of select="/rss/channel/title" /></h1>
            <p class="rss-description">
              <xsl:value-of select="/rss/channel/itunes:subtitle" />
              — Copy the feed URL below to subscribe in any podcast app.
            </p>

            <!-- COPY BOX -->
            <div class="copy-box" id="copy-box">
              <span class="copy-label">RSS</span>
              <span class="copy-url" id="rss-url">
                <xsl:value-of select="/rss/channel/atom:link/@href" />
              </span>
              <button class="copy-btn" id="copy-btn" onclick="copyRSS()" type="button">Copy</button>
            </div>

            <!-- STATS -->
            <div class="stats-row">
              <div class="stat">
                <strong><xsl:value-of select="count(/rss/channel/item)" /></strong>
                Episodes
              </div>
              <div class="stat">
                <strong><xsl:value-of select="/rss/channel/itunes:author" /></strong>
                Author
              </div>
              <div class="stat">
                <strong>Daily · 7AM CET</strong>
                Schedule
              </div>
            </div>

            <!-- SUBSCRIBE BUTTONS -->
            <div class="subscribe-row">
              <a href="#" class="sub-btn primary">+ Add to Podcast App</a>
              <a href="https://podcasts.apple.com" class="sub-btn" target="_blank" rel="noopener">Apple Podcasts</a>
              <a href="https://spotify.com" class="sub-btn" target="_blank" rel="noopener">Spotify</a>
              <a href="/about.html" class="sub-btn">Methodology</a>
            </div>
          </div>
        </div>

        <!-- EPISODES LIST -->
        <main>
          <p class="episodes-header">All episodes — latest first</p>

          <xsl:apply-templates select="/rss/channel/item" />
        </main>

        <footer>
          <p>
            AI Press Review ·
            <a href="/">Home</a> ·
            <a href="/about.html">Methodology</a> ·
            <a href="mailto:david.perron@aequitus.net">Contact</a>
          </p>
        </footer>

        <script>
          function copyRSS() {
            var url = document.getElementById('rss-url').textContent.trim();
            var btn = document.getElementById('copy-btn');
            if (navigator.clipboard) {
              navigator.clipboard.writeText(url).then(function() {
                btn.textContent = 'Copied ✓';
                btn.classList.add('copied');
                setTimeout(function(){ btn.textContent='Copy'; btn.classList.remove('copied'); }, 2500);
              });
            } else {
              /* fallback: select text */
              var el = document.getElementById('rss-url');
              var range = document.createRange();
              range.selectNodeContents(el);
              window.getSelection().removeAllRanges();
              window.getSelection().addRange(range);
              btn.textContent = 'Selected ✓';
              setTimeout(function(){ btn.textContent='Copy'; }, 2000);
            }
          }
        </script>
      </body>
    </html>
  </xsl:template>

  <!-- EPISODE TEMPLATE -->
  <xsl:template match="item">
    <article class="episode-item">
      <div>
        <a class="episode-title" href="{link}">
          <xsl:value-of select="title" />
        </a>
        <div class="episode-meta">
          <span><xsl:value-of select="pubDate" /></span>
          <xsl:if test="itunes:episodeType">
            <span><xsl:value-of select="itunes:episodeType" /></span>
          </xsl:if>
        </div>
        <xsl:if test="itunes:summary">
          <p class="episode-summary">
            <xsl:value-of select="itunes:summary" />
          </p>
        </xsl:if>
        <a class="episode-listen" href="{enclosure/@url}">Listen / Download →</a>
      </div>
      <div class="episode-duration">
        <xsl:value-of select="itunes:duration" />
      </div>
    </article>
  </xsl:template>

</xsl:stylesheet>
